sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vittalharishk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vittalharishk/docker-react npm run test